### PR TITLE
prompt testing

### PR DESCRIPTION
**Pull request by SSunnydev**
needs testing

### CODE REVIEW

**Review by vivekpatell3 — APPROVED** [review]

**Review by RishiDuggal — CHANGES_REQUESTED** [review]
Most of these tests don't pass. There are also some major issues with how this is being gone about.

1. you're not providing a guild id
2.  You're only requiring 1 of the 6 functions you use, and you're not requiring it as function
So that's why it's not working at all.

Besides that, we don't actually want to be clogging our DB with test data, you would want to make a database, with sample data, that is local for testing. You might need to alter the dbconn.js file to connect to that temp DB, but that's something we want for this.

Also you only need 1 get prompts test. It has no way of differentiating or limiting itself to get 0, 1, or many prompts.

**Review by ChristianS2001 — APPROVED** [review]

**Review by tup31461 — CHANGES_REQUESTED** [review]
These don't pass; you can take a look at activeHoursTesting as an example for using a dumby DB for testing

**Review by gevdram — APPROVED** [review]

**Review by gevdram — APPROVED** [review]

**Review by vivekpatell3 — COMMENTED** [review]
Not approved

**Comment by tup31461** [comment]
These tests did not pass, and I have taken this ticket. Closing the PR

**Pull request closed without merging**
