### PR TITLE
Bms 114

### PR DESCRIPTION
**Pull request by tup31461**

### CODE REVIEW

**Review by RishiDuggal — CHANGES_REQUESTED** [review]
Looks good, know it works,

Needs to work within the handleusersubmission.js file instead of approver before a merge to main is possible

**Review by vivekpatell3 — DISMISSED** [review]
^

**Review by ChristianS2001 — DISMISSED** [review]
approver file has conflicts, see Rishi's request for an answer

**Comment by tup31461** [comment]
> Looks good, know it works,
> 
> Needs to work within the handleusersubmission.js file instead of approver before a merge to main is possible

Maybe I'm missing something but in approver.js, why are we replying to the submission w/ "Submitted to moderators" when we haven't run the submission through the logic yet to validate the submission?

**Review by RishiDuggal — APPROVED** [review]
it works, dats some good gabagool

**Pull request merged**
